default namespace = "https://www.dita-ot.org/project"


project = 
## Publication project
element project { (includes | deliverable | publication | context)* }

includes =
  ## Include project file
  element include {
    attribute href { xsd:anyURI }
  }

deliverable =
  ## Project deliverable
  element deliverable {
    attribute name { text }?,
    attribute id { xsd:NCName }?,
    ((context | context-ref), output, (publication | publication-ref))
  }

context =
  ## Context
  element context {
    attribute name { text }?,
    attribute id { xsd:NCName }?,
    input,
    profile?
  }

context-ref =
  ## Publication reference
  element context {
    attribute idref { xsd:NCName }
  }

input =
  ## Input resource
  element input {
    attribute href { xsd:anyURI }
  }

## Output directory
output =
  element output {
    attribute href { xsd:anyURI }
  }

profile = 
## Filter and highlight profile
element profile { ditaval+ }

ditaval =
  ## DITAVAL profile resource
  element ditaval {
    attribute href { xsd:anyURI }?,
    text
  }

publication =
  ## Publication
  element publication {
    attribute name { text }?,
    attribute id { xsd:NCName }?,
    attribute transtype { text },
    param*,
    profile?
  }

publication-ref =
  ## Publication reference
  element publication {
    attribute idref { xsd:NCName },
    param*
  }

param =
  ## Publication parameter
  element param {
    attribute name { param-name-other },
    (attribute href { xsd:anyURI }
     | attribute path { xsd:anyURI }
     | attribute value { text })
  }
  | element param { attribute name { param-names-href },        attribute href { xsd:anyURI } }
  | element param { attribute name { param-names-path },        attribute path { xsd:anyURI } }
  | element param { attribute name { param-names-value },       attribute value { text } }
  | element param { attribute name { param-names-yes-no },      attribute value { "yes" | "no" } }
  | element param { attribute name { param-names-true-false },  attribute value { "true" | "false" } }
  | param-defs-enumerated

param-name-other = xsd:NCName -( param-names-href | param-names-path | param-names-value | param-names-yes-no
                                  | param-names-true-false | param-names-enumerated | param-names-excluded )
param-names-href = empty
param-names-path = empty
param-names-value = empty
param-names-yes-no = empty
param-names-true-false = empty
param-defs-enumerated = empty
param-names-enumerated = empty
param-names-excluded = empty

include "project-params.rnc"

start = project
